/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket.exchange.app;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author Yo/Josh
 */
public class TicketExchangeGUI extends javax.swing.JFrame {
   
    /**
     * Creates new form TicketExchangeGUI
     */
    private Seat seatType;
    private ArrayList<Records> details, availableGamesForTrade;
    private boolean emptyVa;
    private boolean characterVa;
    private boolean ageVa;
    //private boolean phoneVa;
    private String fullName;
    ArrayList<Seat> obj;
    private String fName, lName, uniqueID, age, gender, qty, email, phoneNo, cardNumber, month, year, ccv;
    private boolean meal, phoneOffer, emailOffer;
    
    
    public TicketExchangeGUI() {
       
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jScrollPane4.setVisible(false);
        jScrollPane3.setVisible(false);
        jScrollPane5.setVisible(false);
        details = new ArrayList<>();
        fullName = "";
        File file = new File("output.dat");
        if(!file.exists()){
            createSeatsForGames();
            System.out.println("fresh start");
        }
        
        getAvailaibleGames();
        populateScrollPane();

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        premiumCheckBox = new javax.swing.JRadioButton();
        normalCheckBox = new javax.swing.JRadioButton();
        businessCheckBox = new javax.swing.JRadioButton();
        gameCB = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        premiumTP = new javax.swing.JTextPane();
        selectLB = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        businessTP = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        normalTP = new javax.swing.JTextPane();
        exchangeBtn = new javax.swing.JButton();
        nextBtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cardNumTF = new javax.swing.JTextField();
        monthTF = new javax.swing.JTextField();
        yearTF = new javax.swing.JTextField();
        ccvTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        rememberCardCB = new javax.swing.JCheckBox();
        backBtn2 = new javax.swing.JButton();
        nextBtn3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        summaryLB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        summaryTA = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        submitBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        backBtn3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submitIdTF = new javax.swing.JTextField();
        cardSubmitTF = new javax.swing.JTextField();
        backBtn4 = new javax.swing.JButton();
        submitBtn2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        congratzLB = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        availableLB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableSlotLB = new javax.swing.JList<>();
        selectBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fNameTA = new javax.swing.JTextField();
        lNameTA = new javax.swing.JTextField();
        uniqueIDTA = new javax.swing.JTextField();
        ageTA = new javax.swing.JTextField();
        genderTA = new javax.swing.JTextField();
        quantityCombo = new javax.swing.JComboBox<>();
        emailTA = new javax.swing.JTextField();
        phoneTA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mealCheckBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        phoneCheckBox = new javax.swing.JCheckBox();
        emailCheckBox = new javax.swing.JCheckBox();
        nextBtn2 = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        choice1 = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(610, 426));
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 426));
        jPanel1.setRequestFocusEnabled(false);

        premiumCheckBox.setText("Premium");
        premiumCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumCheckBoxActionPerformed(evt);
            }
        });

        normalCheckBox.setText("Normal");
        normalCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalCheckBoxActionPerformed(evt);
            }
        });

        businessCheckBox.setText("Business");
        businessCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessCheckBoxActionPerformed(evt);
            }
        });

        gameCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gameCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameCBActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(premiumTP);

        selectLB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        selectLB.setText("Select A SEAT");

        jScrollPane4.setViewportView(businessTP);

        jScrollPane5.setViewportView(normalTP);

        exchangeBtn.setText("Exchange!");
        exchangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeBtnActionPerformed(evt);
            }
        });

        nextBtn1.setText("Next");
        nextBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(selectLB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(gameCB, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(exchangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(premiumCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(64, 64, 64)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(businessCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(normalCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(selectLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameCB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(businessCheckBox)
                    .addComponent(premiumCheckBox)
                    .addComponent(normalCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exchangeBtn)
                    .addComponent(nextBtn1))
                .addGap(14, 14, 14))
        );

        cardNumTF.setText("Card Number");

        monthTF.setText("MM");

        yearTF.setText("YYYY");

        ccvTF.setText("CCV");

        nameTF.setText("Name on Card");

        rememberCardCB.setText("Remeber this card?");

        backBtn2.setText("Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });

        nextBtn3.setText("Next");
        nextBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(monthTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ccvTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rememberCardCB)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cardNumTF)
                        .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(backBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn3)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cardNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccvTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rememberCardCB)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn3)
                    .addComponent(backBtn2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(410, 220));

        summaryLB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        summaryLB.setText("Summary:");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        summaryTA.setEditable(false);
        summaryTA.setBackground(new java.awt.Color(204, 204, 204));
        summaryTA.setColumns(20);
        summaryTA.setRows(5);
        jScrollPane2.setViewportView(summaryTA);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(summaryLB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(208, 208, 208))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(summaryLB, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        requestBtn.setText("Request");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });

        backBtn3.setText("<");
        backBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(backBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(backBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("CARD");

        backBtn4.setText("<");
        backBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn4ActionPerformed(evt);
            }
        });

        submitBtn2.setText("Submit");
        submitBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardSubmitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(backBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardSubmitTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(submitIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        congratzLB.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        congratzLB.setText("CONGRATZ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(congratzLB, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(congratzLB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        availableLB.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        availableLB.setText("Available Slot");

        availableSlotLB.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(availableSlotLB);

        selectBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        selectBtn.setText("Select");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(availableLB, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(availableLB, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel3.setText("*First name:");

        fNameTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTAActionPerformed(evt);
            }
        });

        lNameTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTAActionPerformed(evt);
            }
        });

        uniqueIDTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uniqueIDTAActionPerformed(evt);
            }
        });

        ageTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTAActionPerformed(evt);
            }
        });

        genderTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTAActionPerformed(evt);
            }
        });

        quantityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        quantityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityComboActionPerformed(evt);
            }
        });

        emailTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTAActionPerformed(evt);
            }
        });

        phoneTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTAActionPerformed(evt);
            }
        });

        jLabel11.setText("Would you like your package to include a meal?");

        mealCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealCheckBoxActionPerformed(evt);
            }
        });

        jLabel12.setText("Do you want to receive future special offer?");

        phoneCheckBox.setText("Phone");
        phoneCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneCheckBoxActionPerformed(evt);
            }
        });

        emailCheckBox.setText("Email");
        emailCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCheckBoxActionPerformed(evt);
            }
        });

        nextBtn2.setText("Next");
        nextBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtn2ActionPerformed(evt);
            }
        });

        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        jLabel13.setText("*Second name:");

        jLabel14.setText("*Unique ID:");

        jLabel4.setText("Age:");

        jLabel5.setText("Gender:");

        jLabel15.setText("*Quantity:");

        jLabel16.setText("*Email:");

        jLabel17.setText("Phone:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mealCheckBox)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(phoneCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailTA, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageTA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(fNameTA, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNameTA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(uniqueIDTA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(genderTA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(19, 19, 19))
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(quantityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phoneTA, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uniqueIDTA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTA)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneCheckBox)
                    .addComponent(emailCheckBox))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn1)
                    .addComponent(nextBtn2))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(596, 596, 596)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void normalCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalCheckBoxActionPerformed
        // TODO add your handling code here:
        seatType = new Seat(obj.get(gameCB.getSelectedIndex()).getGameName(),obj.get(gameCB.getSelectedIndex()).getGamePrice(),
        obj.get(gameCB.getSelectedIndex()).getNormalSeatsAvailable(),obj.get(gameCB.getSelectedIndex()).getBusinessSeatAvailable(),
        obj.get(gameCB.getSelectedIndex()).getPremiumSeatAvailable());
        seatCheckRadioClicked(2);
         System.out.println(obj.get(gameCB.getSelectedIndex()).getGameName() + " " + ((Seat) seatType).getTicketId() );
    }//GEN-LAST:event_normalCheckBoxActionPerformed

    private void gameCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameCBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_gameCBActionPerformed

    private void nextBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtn3ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(true); //go to summary page
        jPanel3.setVisible(false); //close filling card detail page 
        meal = mealCheckBox.isSelected();
        phoneOffer = phoneCheckBox.isSelected();
        emailOffer = emailCheckBox.isSelected();
        /***********/
        fName = fNameTA.getText();
        lName = lNameTA.getText();
        uniqueID = uniqueIDTA.getText();
        age = ageTA.getText();
        gender = genderTA.getText();
        qty = quantityCombo.getSelectedItem().toString();
        email = emailTA.getText();
        phoneNo = phoneTA.getText();
        cardNumber = cardNumTF.getText();
        month = monthTF.getText();
        year = yearTF.getText();
        ccv = ccvTF.getText();
        
        Records records = new Records(fName,lName,uniqueID,age,gender,qty,email,phoneNo,meal,phoneOffer,emailOffer,cardNumber,month,year,ccv);
//        System.out.println("fName: " + records.getfName());
//        System.out.println("lName: "+ records.getlName());
//        System.out.println("uniqueID: "+records.getUniqueID());
//        System.out.println("age: "+ records.getAge());
//        System.out.println("gender: "+records.getGender());
//        System.out.println("qty: "+records.getQty());
//        System.out.println("email: "+records.getEmail());
//        System.out.println("phoneNo: "+records.getPhoneNo());
//        System.out.println("cardNo: "+records.getCardNumber());
//        System.out.println("month: "+records.getMonth());
//        System.out.println("year: "+records.getYear());
//        System.out.println("ccv: "+records.getCcv());
        
//        records.showDetails();
        
        
//        JOptionPane.showMessageDialog(null,details.size());
        readDetails();
        if(checkID()){
            JOptionPane.showMessageDialog(null,"youve already bought a ticket");
        } else{
            details.add(records);
            saveDetails();
        }
//        for(Records i: details){
//            System.out.println(i.getUniqueID());
            
//        }
        
        summaryTA.setText(String.format("Thank you %s.\n Your  %s ticket(s) to %s\n has been successfully purchased and can be your validation codes\n can be found in file.txt",fNameTA.getText(),
        quantityCombo.getSelectedItem(),gameCB.getSelectedItem()));
        writeGamesToFile();
        
    }//GEN-LAST:event_nextBtn3ActionPerformed

    private void exchangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeBtnActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(true);// open submit or request page 
        jPanel1.setVisible(false);//close down selecting seat page
    }//GEN-LAST:event_exchangeBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        jPanel6.setVisible(true);//open filling ID and Card number page
        jPanel5.setVisible(false);//close down submit or request page
    }//GEN-LAST:event_submitBtnActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        // TODO add your handling code here:
        jPanel8.setVisible(true);//open available slot page 
        jPanel5.setVisible(false);//close down submit or request page
        
        
    }//GEN-LAST:event_requestBtnActionPerformed

    private void backBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn3ActionPerformed
        // TODO add your handling code here: //go back to jPanel1
        jPanel1.setVisible(true);// go back to selecting seat page
        jPanel5.setVisible(false);// close down submit or request page
    }//GEN-LAST:event_backBtn3ActionPerformed

    private void backBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn4ActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(true);//open submit or request page
        jPanel6.setVisible(false);//close down seeat ID and card number page 
    }//GEN-LAST:event_backBtn4ActionPerformed

    private void submitBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtn2ActionPerformed
        // TODO add your handling code here:
        
        readDetails();
        boolean isSubmitted = false;
        for(int i = 0; i < details.size(); i++) {
            System.out.println(details.get(i).getUniqueID());
            if(details.get(i).getUniqueID().equals(submitIdTF.getText()) && details.get(i).getCardNumber().equals(cardSubmitTF.getText())) {
                jPanel7.setVisible(true);// open congratz page, submitting seat ID and card number successfully  
                jPanel6.setVisible(false);// close down seat ID and card Number page 
                isSubmitted = true;
                addNewAvailableTicket(details.get(i));
                //Create a new function to write the item to a new file
                details.remove(i);
                saveDetails();
            }
//            System.out.println(details.get(i).getUniqueID().equals(submitIdTF.getText()));
        }
        if (!isSubmitted) {
            JOptionPane.showMessageDialog(null, "Unsuccessful");
        }
        
    }//GEN-LAST:event_submitBtn2ActionPerformed
    public void populateScrollPane(){
//        availableSlotLB.getViewport().remove(1);
//        jScrollPane1.removeAll();
//         jScrollPane1.add(listModel);

//        jScrollPane1.add(availableSlotLB, "1");
//        availableSlotLB.addElement(gameCB.getSelectedItem());
//        availableSlotLB.addItem
//        jList1.add(this, WIDTH);        
//        jList1.add(fName, jScrollPane1);

//        availableSlotLB.
//        availableSlotLB.add("s");
//        System.out.println(availableSlotLB.getSelectedValue());
//        System.out.println(jScrollPane1.getSize());
//        jScrollPane1.getSize();
//          availableSlotLB.remove(1);

    }
    public void addNewAvailableTicket(Records newGame){
        try{
            File f = new File("Trading.dat");
            FileInputStream input = new FileInputStream(f);
            ObjectInputStream ois = new ObjectInputStream(input);
            availableGamesForTrade = (ArrayList<Records>) ois.readObject();
//            JOptionPane.showMessageDialog(null,details.size());
            ois.close();
//            for (Records i: details) {
//                System.out.println("Name: " + i.getfName());
//            }
        } catch(IOException | ClassNotFoundException e){
            System.out.println("crashing on read " + e);


        } 
        
        availableGamesForTrade.add(newGame);
       
                try{
            
            File file = new File("Trading.dat");
            FileOutputStream output = new FileOutputStream(file);
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(output);            
            objectOutputStream.writeObject(availableGamesForTrade);
            objectOutputStream.close();
            
        } catch(IOException e){
            System.out.println("Crashing on read");
        }
    
    try{
            
            File file = new File("Trading.dat");
            FileOutputStream output = new FileOutputStream(file);
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(output);            
            objectOutputStream.writeObject(availableGamesForTrade);
            objectOutputStream.close();

        } catch(IOException e){
            System.out.println("Crashing on write");
        }            
        
    }
    
    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(true);// go back to filling detail page
        jPanel3.setVisible(false);// close down filling card detail page
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void fNameTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTAActionPerformed

    private void lNameTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTAActionPerformed

    private void uniqueIDTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uniqueIDTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uniqueIDTAActionPerformed

    private void ageTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTAActionPerformed

    private void genderTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTAActionPerformed

    private void quantityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityComboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_quantityComboActionPerformed

    private void emailTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTAActionPerformed

    private void phoneTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTAActionPerformed

    private void mealCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mealCheckBoxActionPerformed

    private void phoneCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneCheckBoxActionPerformed

    private void emailCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCheckBoxActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);// go back to seat page
        jPanel2.setVisible(false);//close filling detail page
        
        
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void nextBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtn2ActionPerformed
        // TODO add your handling code here:
        emptyValidation();
        nameValidation();
        ageValidation();
        //phoneValidation();

        
        //validate required fields
//        if(emptyVa == false){
//            JOptionPane.showMessageDialog(null, "Please fill in required details");
//            
//        } 
//        
//        //validate if the fName and lName only contains character not numbers and special letter
//        else if(characterVa == false){
//            JOptionPane.showMessageDialog(null, "Only alphabets are allowed in this field");
//        }
//        
//        //validate if the age fields only contains numbers and prevent users to put in unrealistic age
//        
//        else if(ageVa == false || Integer.parseInt(ageTA.getText()) > 100){// age can,t be above 100
//            JOptionPane.showMessageDialog(null, "Please type in an appropriate age!");
//        } else {
            jPanel3.setVisible(true);// open filling card detail page
            jPanel2.setVisible(false);//close filling detail page  
            
//            activeIndex = gameCB.getSelectedIndex();
            
            if(seatType instanceof Seat){
                obj.get(gameCB.getSelectedIndex()).setNormalSeatsAvailable(obj.get(gameCB.getSelectedIndex()).getNormalSeatsAvailable()-1);
            } else if(seatType instanceof BusinessSeat){
                obj.get(gameCB.getSelectedIndex()).setBusinessSeatAvailable(obj.get(gameCB.getSelectedIndex()).getBusinessSeatAvailable()-1);
            } else {
                obj.get(gameCB.getSelectedIndex()).setPremiumSeatAvailable(obj.get(gameCB.getSelectedIndex()).getPremiumSeatAvailable()-1);
                
            }
            System.out.println(obj.get(gameCB.getSelectedIndex()).getBusinessSeatAvailable());
//        }
        
        /*
        if(phoneVa == false){
            JOptionPane.showMessageDialog(null, "Please type in an appropriate phone number!");
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
        }
       */
        
    }//GEN-LAST:event_nextBtn2ActionPerformed
    public boolean emptyValidation(){// check if the required text fields are empty
        emptyVa = true;
        if(fNameTA.getText().equals("") || lNameTA.getText().equals("") || uniqueIDTA.getText().equals("") || emailTA.getText().equals("")){
            emptyVa = false;
        }
        return emptyVa;
    }
    
    
    public boolean nameValidation(){ // check if the first name and last name contains character not numbers
        characterVa = true;
        fullName = fNameTA.getText() + lNameTA.getText();
        for(char letter : fullName.toCharArray()){
            if(!Character.isLetter(letter)){
                characterVa = false;
            }
        }
        return characterVa;
    }
    
    public boolean ageValidation(){// check if the inout age is appropriate, can't contain a character
        ageVa = true;
        for(char letter : ageTA.getText().toCharArray()){
            if(!Character.isDigit(letter)){
                ageVa = false;
            }
        }
        return ageVa;
    }
    
    public void createSeatsForGames(){
        try{
            
            File file = new File("output.dat");
            FileOutputStream output = new FileOutputStream(file);
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(output);
            String[] x = {"Ireland v South Africa",
                "Ireland v South Africa & Argentina",
                "Ireland v South Africa & Fiji",
                "Ireland v South Africa, Fiji & Argentina",
                "Ireland v Fiji",
                "Supporters Club Event",
                "Ireland v Argentina"
            };
            ArrayList<Seat> y = new ArrayList<>();
            Seat game;
            Random random = new Random();
            for(String i: x){
                game = new Seat(i,random.nextInt(20)+50,100,100,100);
                y.add(game);
//                System.out.println(1);

            }
            
            objectOutputStream.writeObject(y);
            objectOutputStream.close();

        } catch(IOException e){
            
        }
    }
    
        public void writeGamesToFile(){
        try{
            
            File file = new File("output.dat");
            FileOutputStream output = new FileOutputStream(file);
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(output);
//            String[] x = {"Ireland v South Africa",
//                "Ireland v South Africa & Argentina",
//                "Ireland v South Africa & Fiji",
//                "Ireland v South Africa, Fiji & Argentina",
//                "Ireland v Fiji",
//                "Supporters Club Event",
//                "Ireland v Argentina"
//            };
//            ArrayList<Game> y = new ArrayList<>();
//            Game game;
//            Random random = new Random();
//            for(String i: x){
//                game = new Game(i,random.nextInt(20)+50,100,100,100);
//                y.add(game);
////                System.out.println(1);
//
//            }
            
            objectOutputStream.writeObject(obj);
            objectOutputStream.close();

        } catch(IOException e){
            System.out.println("Crashing on write");
        }
    }
        
        public void getAvailaibleGames(){
        gameCB.removeAllItems();        
        try{
            File file = new File("output.dat");
            FileInputStream input = new FileInputStream(file);
            ObjectInputStream objectInputStream = new ObjectInputStream(input);
            obj = (ArrayList<Seat>) objectInputStream.readObject();
            for(Seat i: obj){
//                System.out.println(1);
                gameCB.addItem(String.format("%s (%s)",i.getGameName(), i.getGamePrice()));
            }
//            String obj[] = (String []) objectInputStream.readObject();
//            for(String i: obj){
//                gameCB.addItem(i);
//            }
            objectInputStream.close();

        } catch(IOException | ClassNotFoundException e){
            System.out.println(e);
        }
    }
        
   
    
    /*
    public boolean phoneValidation(){//check if the phone text field contains only numbers
        phoneVa = true;
        String phone = phoneTA.getText();
        for(int i=0; i< phone.length();i++){
            if(phone.indexOf(0) == '+'){
                phoneVa = true;
            }else if(!Character.isDigit(phone))
        }
        
        return phoneVa;
    }
    */
    
    public Boolean checkID(){
            //System.out.println(1);
        for(Records i: details){
            System.out.println("unique id: " + i.getUniqueID());
            if(i.getUniqueID().equals(uniqueIDTA.getText())){
                return true;
            }
        }
        return false;
    }
    public void saveDetails(){
        try{
            File f = new File("Records.dat");
            FileOutputStream output = new FileOutputStream(f);
            ObjectOutputStream oos = new ObjectOutputStream(output);
            oos.writeObject(details);
            JOptionPane.showMessageDialog(null,"Written!");

            oos.close();
            
        } catch (IOException e){
            System.out.println(e);
            
        }
       
    }
    
    public void readDetails(){
        try{
            File f = new File("Records.dat");
            FileInputStream input = new FileInputStream(f);
            ObjectInputStream ois = new ObjectInputStream(input);
            details = (ArrayList<Records>) ois.readObject();
            JOptionPane.showMessageDialog(null,details.size());
            ois.close();
            for (Records i: details) {
//                System.out.println("Name: " + i.getfName());
            }
        } catch(IOException | ClassNotFoundException e){
            System.out.println("crashing on read");

        } 
       
    }
    
    private void premiumCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiumCheckBoxActionPerformed
        // TODO add your handling code here:
        seatType = new PremiumSeat(obj.get(gameCB.getSelectedIndex()).getGameName(),obj.get(gameCB.getSelectedIndex()).getGamePrice(),
        obj.get(gameCB.getSelectedIndex()).getNormalSeatsAvailable(),obj.get(gameCB.getSelectedIndex()).getBusinessSeatAvailable(),
        obj.get(gameCB.getSelectedIndex()).getPremiumSeatAvailable());
        seatCheckRadioClicked(1);
    }//GEN-LAST:event_premiumCheckBoxActionPerformed

    private void businessCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessCheckBoxActionPerformed
        // TODO add your handling code here:
        seatType = new BusinessSeat(obj.get(gameCB.getSelectedIndex()).getGameName(),obj.get(gameCB.getSelectedIndex()).getGamePrice(),
        obj.get(gameCB.getSelectedIndex()).getNormalSeatsAvailable(),obj.get(gameCB.getSelectedIndex()).getBusinessSeatAvailable(),
        obj.get(gameCB.getSelectedIndex()).getPremiumSeatAvailable());
        seatCheckRadioClicked(0);
    }//GEN-LAST:event_businessCheckBoxActionPerformed

    private void nextBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtn1ActionPerformed
        // TODO add your handling code here:
        if(!businessCheckBox.isSelected() && !premiumCheckBox.isSelected() && !normalCheckBox.isSelected()){
            JOptionPane.showMessageDialog(null,"Please Select a seat.");
        } else{
            jPanel2.setVisible(true);// open filling details page
            jPanel1.setVisible(false);// close seat page (first page)  
        }

        
    }//GEN-LAST:event_nextBtn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Thank You!");
        System.exit(1);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void seatCheckRadioClicked(int clicked){
        JRadioButton x[] = {businessCheckBox,premiumCheckBox,normalCheckBox};
        JScrollPane y[] = {jScrollPane4,jScrollPane3,jScrollPane5};
        JTextPane z[] = {businessTP,premiumTP,normalTP};
        

        for(int i =0; i < x.length; i++){
                if(i == clicked){
                    x[i].setSelected(true);
                    y[i].setVisible(true);

                    z[i].setText(String.format("%s\n%s\n%s",seatType.getSeatName(),seatType.getSeatPrice(),seatType.getSeatArea()));
                    
                } else {
                    x[i].setSelected(false);
                    y[i].setVisible(false);
                }

            
        }
        getContentPane().validate();
        getContentPane().repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketExchangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketExchangeGUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTA;
    private javax.swing.JLabel availableLB;
    private javax.swing.JList<String> availableSlotLB;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backBtn2;
    private javax.swing.JButton backBtn3;
    private javax.swing.JButton backBtn4;
    private javax.swing.JRadioButton businessCheckBox;
    private javax.swing.JTextPane businessTP;
    private javax.swing.JTextField cardNumTF;
    private javax.swing.JTextField cardSubmitTF;
    private javax.swing.JTextField ccvTF;
    private java.awt.Choice choice1;
    private javax.swing.JLabel congratzLB;
    private javax.swing.JCheckBox emailCheckBox;
    private javax.swing.JTextField emailTA;
    private javax.swing.JButton exchangeBtn;
    private javax.swing.JTextField fNameTA;
    private javax.swing.JComboBox<String> gameCB;
    private javax.swing.JTextField genderTA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField lNameTA;
    private javax.swing.JCheckBox mealCheckBox;
    private javax.swing.JTextField monthTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton nextBtn1;
    private javax.swing.JButton nextBtn2;
    private javax.swing.JButton nextBtn3;
    private javax.swing.JRadioButton normalCheckBox;
    private javax.swing.JTextPane normalTP;
    private javax.swing.JCheckBox phoneCheckBox;
    private javax.swing.JTextField phoneTA;
    private javax.swing.JRadioButton premiumCheckBox;
    private javax.swing.JTextPane premiumTP;
    private javax.swing.JComboBox<String> quantityCombo;
    private javax.swing.JCheckBox rememberCardCB;
    private javax.swing.JButton requestBtn;
    private javax.swing.JButton selectBtn;
    private javax.swing.JLabel selectLB;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton submitBtn2;
    private javax.swing.JTextField submitIdTF;
    private javax.swing.JLabel summaryLB;
    private javax.swing.JTextArea summaryTA;
    private javax.swing.JTextField uniqueIDTA;
    private javax.swing.JTextField yearTF;
    // End of variables declaration//GEN-END:variables
}
